# Argonaut digital collection generator, campus collections theme

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
title: Argonaut Digital Collection

description: > 
  A digital collection of University of Idaho student newspaper, the Argonaut, from 1898 to 2010.

# site urls
url: https://www.lib.uidaho.edu 
baseurl: /digital/argonaut
objects: https://www.lib.uidaho.edu/digital/objects/argonaut

# historic vars
digurl: "https://www.lib.uidaho.edu/digital/argonaut"
# urls for references outside collection
liburl: "https://www.lib.uidaho.edu"
repourl: "https://digital.lib.uidaho.edu"
# Build settings
markdown: kramdown

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'argonaut_years'
    template: 'year'
    name: 'title'
    dir: 'years'
    extension: 'html'
