# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Argonaut Digital Collection

description: > 
  A digital collection of University of Idaho student newspaper, the Argonaut, from 1898 to 2010.
# relative url
baseurl: "/digital/argonaut"
# site urls
url: "https://www.lib.uidaho.edu" # the base hostname & protocol for your site
digurl: "https://www.lib.uidaho.edu/digital/argonaut"
# urls for references outside collection
liburl: "https://www.lib.uidaho.edu"
repourl: "https://digital.lib.uidaho.edu"

# Build settings
markdown: kramdown

# deploy commands https://gist.github.com/evanwill/12af569da8b53f037d4f507a0254f76c
# deploy:
# - rsync -r ./ ../../test/

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'argoyears'
    template: 'year'
    name: 'date'
    dir: 'years'
    extension: 'html'
