# Argonaut digital collection generator, campus collections theme

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
title: Argonaut Digital Collection

description: "A digital collection of University of Idaho's student newspaper, The Argonaut, containing more than 6,500 issues from 1898 to 2021."

# site urls
url: https://www.lib.uidaho.edu 
baseurl: /digital/argonaut
# objects location
objects: https://objects.lib.uidaho.edu/argonaut

# location of code, the full url to your github repository
source-code: https://github.com/uidaholib/argonaut_source
# contentdm collection name, matches collection ID used by CDM
cdm-collection-id: argonaut
# CONTENTdm server url
cdm-url: https://digital.lib.uidaho.edu

keywords: University of Idaho; Moscow (Idaho)--Newspapers; University of Idaho--Newspapers; Student Newspaper, History, students, campus, alumni, sports, life, culture

featured-image: https://objects.lib.uidaho.edu/argonaut/years/argonaut1898a.jpg
featured-image-alt: The Argonaut's first issue cover

# Organization branding
organization-name: "University of Idaho Library Digital Collections"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/images/ui_library_horizontal.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/liblogo_white.png

# historic vars
digurl: "https://www.lib.uidaho.edu/digital/argonaut"
# urls for references outside collection
liburl: "https://www.lib.uidaho.edu"
repourl: "https://digital.lib.uidaho.edu"
# Build settings
markdown: kramdown

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'argonaut_years'
    template: 'year'
    name: 'title'
    dir: 'years'
    extension: 'html'
